package Model.pojos;
// Generated 11/04/2018 12:39:19 PM by Hibernate Tools 4.3.1



/**
 * Socios generated by hbm2java
 */
public class Socios  implements java.io.Serializable {


     private Integer cod;
     private String socio;
     private float tasa;
     private int montom;

    public Socios() {
    }

    public Socios(String socio, float tasa, int montom) {
       this.socio = socio;
       this.tasa = tasa;
       this.montom = montom;
    }
   
    public Integer getCod() {
        return this.cod;
    }
    
    public void setCod(Integer cod) {
        this.cod = cod;
    }
    public String getSocio() {
        return this.socio;
    }
    
    public void setSocio(String socio) {
        this.socio = socio;
    }
    public float getTasa() {
        return this.tasa;
    }
    
    public void setTasa(float tasa) {
        this.tasa = tasa;
    }
    public int getMontom() {
        return this.montom;
    }
    
    public void setMontom(int montom) {
        this.montom = montom;
    }




}


